
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label1;
	private global::Gtk.Entry producto2;
	private global::Gtk.Label label6;
	private global::Gtk.Label label5;
	private global::Gtk.Label label4;
	private global::Gtk.Label label3;
	private global::Gtk.Entry producto3;
	private global::Gtk.Entry subtotal;
	private global::Gtk.Entry Iva;
	private global::Gtk.Entry Total;
	private global::Gtk.Button btnFacturar;
	private global::Gtk.Button btnLimpiar;
	private global::Gtk.Entry producto1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w1.X = 27;
		w1.Y = 59;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("producto 1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w2.X = 27;
		w2.Y = 20;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto2 = new global::Gtk.Entry ();
		this.producto2.CanFocus = true;
		this.producto2.Name = "producto2";
		this.producto2.IsEditable = true;
		this.producto2.InvisibleChar = '●';
		this.fixed1.Add (this.producto2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto2]));
		w3.X = 249;
		w3.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.label6);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
		w4.X = 25;
		w4.Y = 284;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Iva");
		this.fixed1.Add (this.label5);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
		w5.X = 23;
		w5.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.label4);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
		w6.X = 22;
		w6.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("producto 3");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w7.X = 24;
		w7.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto3 = new global::Gtk.Entry ();
		this.producto3.CanFocus = true;
		this.producto3.Name = "producto3";
		this.producto3.IsEditable = true;
		this.producto3.InvisibleChar = '●';
		this.fixed1.Add (this.producto3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto3]));
		w8.X = 249;
		w8.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.subtotal = new global::Gtk.Entry ();
		this.subtotal.CanFocus = true;
		this.subtotal.Name = "subtotal";
		this.subtotal.IsEditable = true;
		this.subtotal.InvisibleChar = '●';
		this.fixed1.Add (this.subtotal);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.subtotal]));
		w9.X = 249;
		w9.Y = 166;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Iva = new global::Gtk.Entry ();
		this.Iva.CanFocus = true;
		this.Iva.Name = "Iva";
		this.Iva.IsEditable = true;
		this.Iva.InvisibleChar = '●';
		this.fixed1.Add (this.Iva);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Iva]));
		w10.X = 245;
		w10.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Total = new global::Gtk.Entry ();
		this.Total.CanFocus = true;
		this.Total.Name = "Total";
		this.Total.IsEditable = true;
		this.Total.InvisibleChar = '●';
		this.fixed1.Add (this.Total);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Total]));
		w11.X = 246;
		w11.Y = 267;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFacturar = new global::Gtk.Button ();
		this.btnFacturar.CanFocus = true;
		this.btnFacturar.Name = "btnFacturar";
		this.btnFacturar.UseUnderline = true;
		this.btnFacturar.Label = global::Mono.Unix.Catalog.GetString ("FACTURAR");
		this.fixed1.Add (this.btnFacturar);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnFacturar]));
		w12.X = 122;
		w12.Y = 379;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLimpiar = new global::Gtk.Button ();
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("Limpiar");
		this.fixed1.Add (this.btnLimpiar);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnLimpiar]));
		w13.X = 308;
		w13.Y = 376;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.producto1 = new global::Gtk.Entry ();
		this.producto1.CanFocus = true;
		this.producto1.Name = "producto1";
		this.producto1.IsEditable = true;
		this.producto1.InvisibleChar = '●';
		this.fixed1.Add (this.producto1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.producto1]));
		w14.X = 246;
		w14.Y = 12;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 617;
		this.DefaultHeight = 502;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnFacturar.Clicked += new global::System.EventHandler (this.OnBtnFacturarClicked);
		this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
	}
}
